name: FTP Deploy

on:
  push:
    branches:
      - main  # Il ramo su cui vuoi attivare il deploy, puoi cambiarlo se usi un altro ramo

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout del repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Step 2: Connessione al server FTP e upload
      - name: Deploy via FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_SERVER }}    # Definito nei secrets
          username: ${{ secrets.FTP_USERNAME }}  # Definito nei secrets
          password: ${{ secrets.FTP_PASSWORD }}  # Definito nei secrets
          local-dir: ./  # La directory locale da cui caricare (usa ./ per la root del repo)
          server-dir: /path/on/server  # La directory sul server FTP dove vuoi fare il deploy
